//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiMC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiMC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutIcon {
            get {
                object obj = ResourceManager.GetObject("AboutIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brick {
            get {
                object obj = ResourceManager.GetObject("brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/Changelog.txt.
        /// </summary>
        internal static string ChangelogURL {
            get {
                return ResourceManager.GetString("ChangelogURL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CheckUpdateIcon {
            get {
                object obj = ResourceManager.GetObject("CheckUpdateIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multimc.cfg.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap diamond {
            get {
                object obj = ResourceManager.GetObject("diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_import {
            get {
                object obj = ResourceManager.GetObject("document_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/Ionic.Zip.Reduced.dll.
        /// </summary>
        internal static string DotNetZipURL {
            get {
                return ResourceManager.GetString("DotNetZipURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/.
        /// </summary>
        internal static string DownloadSiteURL {
            get {
                return ResourceManager.GetString("DownloadSiteURL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap enderman {
            get {
                object obj = ResourceManager.GetObject("enderman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dl.dropbox.com/u/52412912/LWJGL/.
        /// </summary>
        internal static string ForkkMCDownloadUrl {
            get {
                return ResourceManager.GetString("ForkkMCDownloadUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gold {
            get {
                object obj = ResourceManager.GetObject("gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grass {
            get {
                object obj = ResourceManager.GetObject("grass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpIcon {
            get {
                object obj = ResourceManager.GetObject("HelpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImportIcon {
            get {
                object obj = ResourceManager.GetObject("ImportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iron {
            get {
                object obj = ResourceManager.GetObject("iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastlogin.
        /// </summary>
        internal static string LastLoginFileName {
            get {
                return ResourceManager.GetString("LastLoginFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi[r;Yq&apos;/FKM].@wgZoIBh~bkY}&amp;W,0&gt;)Gz%Jbusexx)&amp;ijhXV}b^8m;&amp;jfL73tx.
        /// </summary>
        internal static string LastLoginKey {
            get {
                return ResourceManager.GetString("LastLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiMCLauncher.
        /// </summary>
        internal static string LauncherClassName {
            get {
                return ResourceManager.GetString("LauncherClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2012 Andrew Okin
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        ///See the License for the specific language govern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/Linux/MultiMC.
        /// </summary>
        internal static string LinuxUpdateURL {
            get {
                return ResourceManager.GetString("LinuxUpdateURL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mc-versions.cfg.
        /// </summary>
        internal static string MCVersionFile {
            get {
                return ResourceManager.GetString("MCVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/mc-versions.cfg.
        /// </summary>
        internal static string MCVersionFileDL {
            get {
                return ResourceManager.GetString("MCVersionFileDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modlist.
        /// </summary>
        internal static string ModListFileName {
            get {
                return ResourceManager.GetString("ModListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://s3.amazonaws.com/MinecraftDownload/.
        /// </summary>
        internal static string MojangMCDownloadUrl {
            get {
                return ResourceManager.GetString("MojangMCDownloadUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MultiMC128 {
            get {
                object obj = ResourceManager.GetObject("MultiMC128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MultiMC32 {
            get {
                object obj = ResourceManager.GetObject("MultiMC32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MultiMC64 {
            get {
                object obj = ResourceManager.GetObject("MultiMC64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewInstIcon {
            get {
                object obj = ResourceManager.GetObject("NewInstIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiMCUpdate.exe.
        /// </summary>
        internal static string NewVersionFileName {
            get {
                return ResourceManager.GetString("NewVersionFileName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap planks {
            get {
                object obj = ResourceManager.GetObject("planks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshInstIcon {
            get {
                object obj = ResourceManager.GetObject("RefreshInstIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RenameIcon {
            get {
                object obj = ResourceManager.GetObject("RenameIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportBugIcon {
            get {
                object obj = ResourceManager.GetObject("ReportBugIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SettingsIcon {
            get {
                object obj = ResourceManager.GetObject("SettingsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stone {
            get {
                object obj = ResourceManager.GetObject("stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tnt {
            get {
                object obj = ResourceManager.GetObject("tnt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install updates because the operation timed out. This may be due to MultiMC not closing properly..
        /// </summary>
        internal static string UpdateTimeoutMessage {
            get {
                return ResourceManager.GetString("UpdateTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/MultiMC.exe.
        /// </summary>
        internal static string UpdateURL {
            get {
                return ResourceManager.GetString("UpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icons.
        /// </summary>
        internal static string UserIconDir {
            get {
                return ResourceManager.GetString("UserIconDir", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ViewFolderIcon {
            get {
                object obj = ResourceManager.GetObject("ViewFolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forkk.net/MultiMC/download/cs-version.
        /// </summary>
        internal static string VInfoUrl {
            get {
                return ResourceManager.GetString("VInfoUrl", resourceCulture);
            }
        }
    }
}
