
// This file has been generated by the GUI designer. Do not modify.
namespace MultiMC
{
	public partial class ConsoleWindow
	{
		private global::Gtk.VBox ConsoleVBox;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView ConsoleView;
		private global::Gtk.HButtonBox ConsoleButtonBox;
		private global::Gtk.Button HideButton;
		private global::Gtk.Button CloseButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiMC.ConsoleWindow
			this.WidthRequest = 600;
			this.HeightRequest = 300;
			this.Name = "MultiMC.ConsoleWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MultiMC Console");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child MultiMC.ConsoleWindow.Gtk.Container+ContainerChild
			this.ConsoleVBox = new global::Gtk.VBox ();
			this.ConsoleVBox.Name = "ConsoleVBox";
			this.ConsoleVBox.Spacing = 6;
			// Container child ConsoleVBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ConsoleView = new global::Gtk.TextView ();
			this.ConsoleView.CanFocus = true;
			this.ConsoleView.Name = "ConsoleView";
			this.ConsoleView.Editable = false;
			this.ConsoleView.CursorVisible = false;
			this.ConsoleView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.ConsoleView);
			this.ConsoleVBox.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ConsoleVBox [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child ConsoleVBox.Gtk.Box+BoxChild
			this.ConsoleButtonBox = new global::Gtk.HButtonBox ();
			this.ConsoleButtonBox.Name = "ConsoleButtonBox";
			this.ConsoleButtonBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ConsoleButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.HideButton = new global::Gtk.Button ();
			this.HideButton.CanFocus = true;
			this.HideButton.Name = "HideButton";
			this.HideButton.UseUnderline = true;
			this.HideButton.BorderWidth = ((uint)(2));
			this.HideButton.Label = global::Mono.Unix.Catalog.GetString ("Hide");
			this.ConsoleButtonBox.Add (this.HideButton);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ConsoleButtonBox [this.HideButton]));
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(4));
			// Container child ConsoleButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.CloseButton = new global::Gtk.Button ();
			this.CloseButton.Sensitive = false;
			this.CloseButton.CanFocus = true;
			this.CloseButton.Name = "CloseButton";
			this.CloseButton.UseUnderline = true;
			this.CloseButton.BorderWidth = ((uint)(2));
			this.CloseButton.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.ConsoleButtonBox.Add (this.CloseButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ConsoleButtonBox [this.CloseButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.ConsoleVBox.Add (this.ConsoleButtonBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ConsoleVBox [this.ConsoleButtonBox]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.ConsoleVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 300;
			this.Show ();
			this.HideButton.Clicked += new global::System.EventHandler (this.OnHideButtonClicked);
			this.CloseButton.Clicked += new global::System.EventHandler (this.OnCloseButtonClicked);
		}
	}
}
