
// This file has been generated by the GUI designer. Do not modify.
namespace MultiMC
{
	public partial class HintDialog
	{
		private global::Gtk.Alignment hintAlignment;
		private global::Gtk.TextView textviewHint;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.CheckButton dontShowCheck;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiMC.HintDialog
			this.WidthRequest = 480;
			this.Name = "MultiMC.HintDialog";
			this.Title = "Hint";
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MultiMC.HintDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hintAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.hintAlignment.Name = "hintAlignment";
			this.hintAlignment.BorderWidth = ((uint)(6));
			// Container child hintAlignment.Gtk.Container+ContainerChild
			this.textviewHint = new global::Gtk.TextView ();
			this.textviewHint.Sensitive = false;
			this.textviewHint.CanFocus = true;
			this.textviewHint.Name = "textviewHint";
			this.textviewHint.Editable = false;
			this.textviewHint.CursorVisible = false;
			this.textviewHint.WrapMode = ((global::Gtk.WrapMode)(2));
			this.hintAlignment.Add (this.textviewHint);
			w1.Add (this.hintAlignment);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.hintAlignment]));
			w3.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(6));
			this.alignment4.RightPadding = ((uint)(6));
			this.alignment4.BottomPadding = ((uint)(2));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.dontShowCheck = new global::Gtk.CheckButton ();
			this.dontShowCheck.CanFocus = true;
			this.dontShowCheck.Name = "dontShowCheck";
			this.dontShowCheck.Label = "Don\'t show this hint again";
			this.dontShowCheck.DrawIndicator = true;
			this.dontShowCheck.UseUnderline = true;
			this.alignment4.Add (this.dontShowCheck);
			w1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment4]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child MultiMC.HintDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 480;
			this.DefaultHeight = 122;
			this.Show ();
		}
	}
}
