
// This file has been generated by the GUI designer. Do not modify.
namespace MultiMC
{
	public partial class ExceptionDialog
	{
		private global::Gtk.VBox vboxContent;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.HBox hboxMessage;
		private global::Gtk.Alignment iconAlignment;
		private global::Gtk.Image iconImage;
		private global::Gtk.TextView textviewMessage;
		private global::Gtk.Expander infoExpander;
		private global::Gtk.VBox vboxInfoExpander;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView infoTextview;
		private global::Gtk.Label infoExpanderLabel;
		private global::Gtk.Button buttonQuit;
		private global::Gtk.Button buttonIgnore;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiMC.ExceptionDialog
			this.WidthRequest = 450;
			this.HeightRequest = 240;
			this.Name = "MultiMC.ExceptionDialog";
			this.Title = "Unhandled Error";
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MultiMC.ExceptionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxContent = new global::Gtk.VBox ();
			this.vboxContent.Name = "vboxContent";
			this.vboxContent.Spacing = 6;
			// Container child vboxContent.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 120;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.hboxMessage = new global::Gtk.HBox ();
			this.hboxMessage.Name = "hboxMessage";
			this.hboxMessage.Spacing = 6;
			// Container child hboxMessage.Gtk.Box+BoxChild
			this.iconAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.iconAlignment.Name = "iconAlignment";
			this.iconAlignment.BorderWidth = ((uint)(16));
			// Container child iconAlignment.Gtk.Container+ContainerChild
			this.iconImage = new global::Gtk.Image ();
			this.iconImage.Name = "iconImage";
			this.iconImage.Xalign = 0F;
			this.iconImage.Yalign = 0F;
			this.iconImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Dialog);
			this.iconAlignment.Add (this.iconImage);
			this.hboxMessage.Add (this.iconAlignment);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxMessage [this.iconAlignment]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxMessage.Gtk.Box+BoxChild
			this.textviewMessage = new global::Gtk.TextView ();
			this.textviewMessage.Buffer.Text = "Error message";
			this.textviewMessage.Sensitive = false;
			this.textviewMessage.CanFocus = true;
			this.textviewMessage.Name = "textviewMessage";
			this.textviewMessage.Editable = false;
			this.textviewMessage.WrapMode = ((global::Gtk.WrapMode)(2));
			this.hboxMessage.Add (this.textviewMessage);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxMessage [this.textviewMessage]));
			w4.Position = 1;
			this.vpaned1.Add (this.hboxMessage);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hboxMessage]));
			w5.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.infoExpander = new global::Gtk.Expander (null);
			this.infoExpander.CanFocus = true;
			this.infoExpander.Name = "infoExpander";
			// Container child infoExpander.Gtk.Container+ContainerChild
			this.vboxInfoExpander = new global::Gtk.VBox ();
			this.vboxInfoExpander.Name = "vboxInfoExpander";
			this.vboxInfoExpander.Spacing = 6;
			// Container child vboxInfoExpander.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.infoTextview = new global::Gtk.TextView ();
			this.infoTextview.CanFocus = true;
			this.infoTextview.Name = "infoTextview";
			this.infoTextview.Editable = false;
			this.infoTextview.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.infoTextview);
			this.vboxInfoExpander.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxInfoExpander [this.GtkScrolledWindow]));
			w7.Position = 0;
			this.infoExpander.Add (this.vboxInfoExpander);
			this.infoExpanderLabel = new global::Gtk.Label ();
			this.infoExpanderLabel.Name = "infoExpanderLabel";
			this.infoExpanderLabel.LabelProp = "More info";
			this.infoExpanderLabel.UseUnderline = true;
			this.infoExpander.LabelWidget = this.infoExpanderLabel;
			this.vpaned1.Add (this.infoExpander);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.infoExpander]));
			w9.Resize = false;
			w9.Shrink = false;
			this.vboxContent.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxContent [this.vpaned1]));
			w10.Position = 0;
			w10.Padding = ((uint)(8));
			w1.Add (this.vboxContent);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.vboxContent]));
			w11.Position = 0;
			// Internal child MultiMC.ExceptionDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonQuit = new global::Gtk.Button ();
			this.buttonQuit.CanDefault = true;
			this.buttonQuit.CanFocus = true;
			this.buttonQuit.Name = "buttonQuit";
			this.buttonQuit.UseStock = true;
			this.buttonQuit.UseUnderline = true;
			this.buttonQuit.Label = "gtk-quit";
			this.AddActionWidget (this.buttonQuit, -8);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonQuit]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonIgnore = new global::Gtk.Button ();
			this.buttonIgnore.CanDefault = true;
			this.buttonIgnore.CanFocus = true;
			this.buttonIgnore.Name = "buttonIgnore";
			this.buttonIgnore.UseStock = true;
			this.buttonIgnore.UseUnderline = true;
			this.buttonIgnore.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonIgnore, -9);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonIgnore]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 558;
			this.DefaultHeight = 240;
			this.Show ();
			this.Response += new global::Gtk.ResponseHandler (this.OnResponse);
		}
	}
}
