
// This file has been generated by the GUI designer. Do not modify.
namespace MultiMC
{
	public partial class BackupListDialog
	{
		private global::Gtk.VBox vboxBackups;
		private global::Gtk.Label labelInfo;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView backupView;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiMC.BackupListDialog
			this.WidthRequest = 600;
			this.HeightRequest = 400;
			this.Name = "MultiMC.BackupListDialog";
			this.Title = "Backups";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MultiMC.BackupListDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxBackups = new global::Gtk.VBox ();
			this.vboxBackups.Name = "vboxBackups";
			this.vboxBackups.Spacing = 6;
			// Container child vboxBackups.Gtk.Box+BoxChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.LabelProp = "Select a backup to restore and click OK.";
			this.vboxBackups.Add (this.labelInfo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxBackups [this.labelInfo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxBackups.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.backupView = new global::Gtk.TreeView ();
			this.backupView.CanFocus = true;
			this.backupView.Name = "backupView";
			this.GtkScrolledWindow.Add (this.backupView);
			this.vboxBackups.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxBackups [this.GtkScrolledWindow]));
			w4.Position = 1;
			w1.Add (this.vboxBackups);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vboxBackups]));
			w5.Position = 0;
			// Internal child MultiMC.BackupListDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			this.Show ();
		}
	}
}
